source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

gem 'sinatra'

gem 'thin'
gem 'puma'
gem 'reel'
gem 'http'
gem 'webrick'

gem 'smarter_csv'
gem "roo", "~> 2.8.0"
gem 'roo-xls'
gem 'rest-client'
gem 'nori'
gem 'dotenv'

gem 'sidekiq'
gem 'sidekiq-cron'