version: '3.0'
services:
  #admin_service:
  #  build: Admin-Service/.
  #  ports:
  #    - "4000:3000"
  #   problem s databazou :(

  dispatcher:
    build: dispatcher/.
    ports:
      - "4001:3000"

  invoices:
    build: invoices/.
    ports:
      - "4002:3000"

  gls_invoices:
    build: gls_invoice/.
    ports:
      - "4003:3000"