version: '3.0'
services:
  #admin_service:
  #  build: Admin-Service/.
  #  ports:
  #    - "4000:3000"
  #   problem s databazou :(

  gls_processor:
    build: processors/.
    ports:
      - "4567:4567"

  saver:
    build: savers/.
