version: '3.0'
services:
  admin_service:
    build: Admin-Service/.
    ports:
      - "4001:3000"
    environment:
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_DB=savers_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
      - SEMANTIC-PROCESSING=true

  processor:
    build: processors/.
    deploy:
      replicas: 0
    environment:
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
    ports:
      - "4560-4570:4567"

  saver:
    build: savers/.
    ports:
        #- "3950-4000:3000"
      - "4000:3000"
    privileged: true
    environment:
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_DB=savers_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379

  sidekiq-heureka:
    build: downloaders/.
    environment:
      - SINGLE=true
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
      - START-JOB=false
      - SCHEDULE-JOB=false
      - CRON='*/5 * * * *'            # ak je scheduled job true, tak nastav CRON cas
    command: bundle exec sidekiq -r ./heureka_reviews_downloader.rb

  sidekiq-sftp:
    build: downloaders/.
    command: bundle exec sidekiq -r ./sftp_csv_downloader.rb -C ./sidekiq.yml
    environment:
      - FILES_PATH=DPD
      - SFTP_HOST=172.17.0.1
      - SFTP_USER=sftp_user
      - SFTP_PASSWORD=postgres
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
      - START-JOB=false
      - SCHEDULE-JOB=false
      - CRON='0 0 * * *'            # ak je scheduled job true, tak nastav CRON cas

  tracking_sidekiq:
    build:
        context: ./Admin-Service
        dockerfile: Dockerfile-sidekiq
    environment:
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
    command: bundle exec sidekiq -C config/sidekiq.yml

  single_reviews:
      build: workers/
      environment:
        - REDIS_HOST=redis-stack-server
        - REDIS_PORT=6379
      privileged: true
      # commented to not start automatically
      #command: bundle exec sidekiq -r ./reviews_sidekiq.rb -C ./sidekiq.yml

  optional-processors:
    build: processors/optional_processors/.
    deploy:
      replicas: 0
    environment:
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
    ports:
      - "5000-5005:4567"

  neo4j:
    ports:
      - '7687:7687'
      - '7474:7474'
    volumes:
      - '$HOME/Data/neo4j/data:/data'
      - '$HOME/Data/neo4j/logs:/logs'
      - '$HOME/Data/neo4j/import:/var/lib/neo4j/import'
      - '$HOME/Data/neo4j/plugins:/plugins'
    environment:
      - 'NEO4J_PLUGINS=["apoc", "n10s"]'
      - NEO4J_AUTH=none
      #- 'NEO4JLABS_PLUGINS=["apoc", "n10s"]'
    image: 'neo4j:5.5.0'

  apach-tika:
    image: 'apache/tika:latest-full'
    ports:
        - '9998:9998'

  semantics:
    build: semantics/.
    ports:
      - "4321:4321"
    environment:
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
      - ONTOLOGY=false
      - TAGGING=true
      - SEMANTIC_DEPLOY=true
    volumes:
      - ./docker-compose.yml:/code/docker-compose.yml

  redis-stack-server:
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./semantics/tags/redis-scoring/hits_scorer.so:/hits_scorer.so
    environment:
      - REDISEARCH_ARGS=EXTLOAD /hits_scorer.so
    image: 'redis/redis-stack:latest'

  tags:
    build: semantics/tags/.
    ports:
      - "4444:4444"
    environment:
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
