version: '3.0'
services:
  admin_service:
    build: Admin-Service/.
    ports:
      - "4001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  processor:
    build: processors/.
    env_file:
      - processors/.env
    ports:
      - "4560-4570:4567"
    links:
      - "saver:saver"
    extra_hosts:
      - host.docker.internal:host-gateway

  saver:
    build: savers/.
    ports:
        - "3950-4000:3000"
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sidekiq-heureka:
    build: downloaders/.
    env_file:
      - downloaders/.env
    environment:
      - SINGLE=true
    entrypoint: bundle
    command: exec sidekiq -r ./heureka_reviews_downloader.rb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sidekiq-sftp:
    build: downloaders/.
    env_file:
      - downloaders/.env
    command: bundle exec sidekiq -r ./sftp_csv_downloader.rb -C ./sidekiq.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tracking_sidekiq:
    build:
        context: ./Admin-Service
        dockerfile: Dockerfile-sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  single_reviews:
      build: workers/
      env_file:
        - workers/.env
      privileged: true
      command: bundle exec sidekiq -r ./reviews_sidekiq.rb -C ./sidekiq.yml
      extra_hosts:
        - "host.docker.internal:host-gateway"

  #tracking_sidekiq:
  #  build: workers/
  #  env_file:
  #    - workers/.env
    #volumes:
    #  - /home/jakzak/Plocha/bakalarka/data-warehouse/Admin-Service/public/files:/data/
  #  command: bundle exec sidekiq -r ./tracking_sidekiq.rb -C ./sidekiq.yml
  #  command: bundle exec sidekiq -r AdminService -C ./workers/sidekiq.yml
