version: '3.0'
services:
  @extract_admin_service:
    build: Admin-Service/.
    ports:
      - "4001:3000"
    environment:
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_DB=admin_development
      - POSTGRES_USER=adam_zak
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - REDIS_SIDEKIQ_URL=redis://172.17.0.1:6379

  @transform_processor:
    build: processors/.
    environment:
      - REDIS_SIDEKIQ_URL=redis://172.17.0.1:6379
    ports:
      - "4560-4570:4567"
    links:
      - "saver:saver"

  @load_saver:
    build: savers/.
    ports:
        - "3950-4000:3000"
    privileged: true
    environment:
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_DB=savers_development
      - POSTGRES_USER=adam_zak
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - REDIS_SIDEKIQ_URL=redis://172.17.0.1:6379

  @extract_sidekiq-heureka:
    build: downloaders/.
    environment:
      - SINGLE=true
      - REDIS_SIDEKIQ_URL=redis://172.17.0.1:6379
      - START-JOB=false
      - SCHEDULE-JOB=true
      - CRON='*/5 * * * *'
    command: bundle exec sidekiq -r ./heureka_reviews_downloader.rb

  @extract_sidekiq-sftp:
    build: downloaders/.
    command: bundle exec sidekiq -r ./sftp_csv_downloader.rb -C ./sidekiq.yml
    environment:
      - FILES_PATH=DPD
      - SFTP_HOST=172.17.0.1
      - SFTP_USER=sftp_user
      - SFTP_PASSWORD=postgres
      - REDIS_SIDEKIQ_URL=redis://172.17.0.1:6379
      - START-JOB=false
      - SCHEDULE-JOB=false
      - CRON='0 0 * * *'

  @extract_tracking_sidekiq:
    build:
        context: ./Admin-Service
        dockerfile: Dockerfile-sidekiq
    environment:
      - REDIS_SIDEKIQ_URL=redis://172.17.0.1:6379
    command: bundle exec sidekiq -C config/sidekiq.yml

  @transform_single_reviews:
      build: workers/
      environment:
        - REDIS_SIDEKIQ_URL=redis://172.17.0.1:6379
      privileged: true
      command: bundle exec sidekiq -r ./reviews_sidekiq.rb -C ./sidekiq.yml
