version: '3.0'
services:
  admin_service:
    build: Admin-Service/.
    #entrypoint: /bin/docker-entrypoint.sh
    ports:
      - "4001:3000"

  processor:
    build: processors/.
    env_file:
      - processors/.env
    ports:
      - "4567-4570:4567"
    links:
      - "saver:saver"

  saver:
    build: savers/.
    ports:
        - "3950-4000:3000"
    #ports:
    #  - "4000:3000"
  ###########################################

  #heureka_dowloader:
  #  build: downloaders/.
  #  env_file:
  #    - downloaders/.env
  #  depends_on:
  #    - sidekiq

  #########################################
  sidekiq-heureka:
    build: downloaders/.
    env_file:
      - downloaders/.env
    entrypoint: bundle
    command: exec sidekiq -r ./heureka_reviews_downloader.rb

  sidekiq-sftp:
    build: downloaders/.
    env_file:
      - downloaders/.env
    entrypoint: bundle
    command: exec sidekiq -r ./sftp_csv_downloader.rb -C ./sidekiq.yml
    volumes:
     - /home/jakzak/Plocha/bakalarka/data-warehouse/downloaders/DPD:/DPD/

  tracking_sidekiq:
    build:
        context: ./Admin-Service
        dockerfile: Dockerfile-sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml

  single_reviews:
      build: workers/
      env_file:
        - workers/.env
      #entrypoint: bundle
      command: bundle exec sidekiq -r ./reviews_sidekiq.rb -C ./sidekiq.yml

  #tracking_sidekiq:
  #  build: workers/
  #  env_file:
  #    - workers/.env
    #volumes:
    #  - /home/jakzak/Plocha/bakalarka/data-warehouse/Admin-Service/public/files:/data/
    #command: bundle exec sidekiq -r ./tracking_sidekiq.rb -C ./sidekiq.yml
  #  command: bundle exec sidekiq -r AdminService -C ./workers/sidekiq.yml