source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

## SINATRA gem
gem 'sinatra'

gem 'thin'
gem 'puma'
gem 'reel'
gem 'http'
gem 'webrick'

gem 'redis'
