source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'sinatra'

gem 'thin'
gem 'puma'
gem 'reel'
gem 'http'
gem 'webrick'

gem 'activesupport', '~> 7.0', '<= 7.0.8'
gem 'activegraph', '>= 10.0.0'
gem 'neo4j-ruby-driver'

gem 'rest-client'
gem 'dotenv'

gem 'sidekiq'
gem 'sidekiq-cron'